### ISSUE TITLE
Does not seem to play nice with gulp-plumber

### ISSUE THREAD

**Issue by nsainaney** [robrich/gulp-if#57]
If you have a task like so:

```
var gulpif = require('gulp-if');
var plumber = require('gulp-plumber');

gulp.src(['**.js'])
  .pipe(plumber()) // To catch any errors
  .piple(gulpif(condition, babel()))
  ... (loads of other pipe's for source mapping etc.
  .pipe(gulp.dest())
```

And put the above in a watch, the watch task crashes if babel fails. It seems that errors don't get propagated to plumber. Any suggested workarounds?

**Comment by rval** [comment]
+1. Having the same issue.

**Comment by robrich** [comment]
rval, have a repro github or pastebin?

**Comment by rval** [comment]
@robrich: Apologies for the late response on this. I've setup a [repository](https://github.com/rval/gulp-if-issue) that demonstrates the issue. Reproduction steps are in [index.js](https://github.com/rval/gulp-if-issue/blob/master/index.js). 

Let me know if I missed anything. Thanks!

**Comment by alpadev** [comment]
Hey there!

I'd like to share my findings since I have a similiar problem (though with in combination of lazypipe).

To prevent gulp.watch from breaking I was using something like (instead of plumber):

```js
lazypipe().on('error', function () {
    this.emit('end');
});
```

It looks like *ternary-stream* causes that event bubbling to break.

When I use gulpif with a boolean condition like so:

```js
gulp.src('*.js')
    .pipe(gulpif(true, lazypipe().on('error', function () {
        this.emit('end');
    }));
```

as far as I get it that lazypipe is used directly and watch doesn't break.

When used with a path condition:

```js
gulp.src('*.js')
    .pipe(gulpif('*.js', lazypipe().on('error', function () {
        this.emit('end');
    }));
```

it's using that ternary-stream instead and it breaks the watch process because (in my case) it looks like the *end*-event is never redirected.

In case of rval's problem when used with a boolean condition it works like one would expect but also fails when using e.g. a string and thus the ternary-stream.

By attaching event handlers I found out that things getting stalled after piping erroneous data to trueStream.

w/o syntax-error:
```
forkStream A Data
trueStream Data
outStream Data
index.js changed
```

with syntax-error:
```
forkStream A Data
trueStream Err
outStream Err
index.js changed
duplexify Err
ternaryStream Err
```

**Comment by Gcaufy** [comment]
I have the same problem, I tried @rval 's demo, and I tried @alpadev 's `on('error', ...`. it still doesn't work

**Comment by Gcaufy** [comment]
![gulp-if](https://user-images.githubusercontent.com/2182004/33868110-03c612b0-df3c-11e7-9ce5-470b19695711.gif)

**Comment by soulcreate** [comment]
Resolved. You must don't use gulp-if. Use separate gulp tasks.

**Comment by robrich** [comment]
I debugged this for a really long time, and found the answer.  `gulp-plumber` monkey-patches all streams from now on, but doesn't reach back in time to pipe pre-existing streams.  `gulp-if` wraps a few streams into a meta-stream, and presents the one meta-stream to the gulp process.  This means `gulp-plumber` doesn't reach into these inner streams, and thus can't "plumb" them.  This is a limitation of `gulp-plumber` and should be addressed there.

So how would `gulp-plumber` solve this?  I don't know, and this is why I hesitated posting this.  I'm not sure if `gulp-plumber` can climb back up the stream to discover (and "plumb") all streams everywhere, or if it only gets a handle to the last stream.
