### ISSUE TITLE
'gulp-if' is not in the npm registry.

### ISSUE THREAD

**Issue by kamal2222ahmed** [robrich/gulp-if#74]
trying to install gulp-if using Jenkins, here is the portion of the log related to gulp-if

00:03:02.398 npm ERR! Linux 2.6.32-431.29.2.el6.x86_64
00:03:02.398 npm ERR! argv "/opt/nodejs/node-v4.4.7-linux-x64/bin/node" "/usr/bin/npm" "install"
00:03:02.398 npm ERR! node v4.4.7
00:03:02.399 npm ERR! npm  v2.15.8
00:03:02.399 npm ERR! code E404
00:03:02.400 
00:03:02.401 npm ERR! 404 Not found : gulp-if
00:03:02.401 npm ERR! 404 
00:03:02.401 npm ERR! 404 'gulp-if' is not in the npm registry.
00:03:02.402 npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by robrich** [comment]
npmjs.org/gulp-if. Are you behind a particularly stringent firewall? npm
cache clean and see if that gets you unclogged.

On May 16, 2017 9:57 PM, "kamal2222ahmed" <notifications@github.com> wrote:

trying to install gulp-if using Jenkins, here is the portion of the log
related to gulp-if

00:03:02.398 npm ERR! Linux 2.6.32-431.29.2.el6.x86_64
00:03:02.398 npm ERR! argv "/opt/nodejs/node-v4.4.7-linux-x64/bin/node"
"/usr/bin/npm" "install"
00:03:02.398 npm ERR! node v4.4.7
00:03:02.399 npm ERR! npm v2.15.8
00:03:02.399 npm ERR! code E404
00:03:02.400
00:03:02.401 npm ERR! 404 Not found : gulp-if
00:03:02.401 npm ERR! 404
00:03:02.401 npm ERR! 404 'gulp-if' is not in the npm registry.
00:03:02.402 npm ERR! 404 You should bug the author to publish it (or use
the name yourself!)

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/robrich/gulp-if/issues/74>, or mute the thread
